api/urls.py
from rest_framework import routers
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from django.urls import path, include
from api import views
from api.token_view import AddUsernameTokenObtainPairView


app_name = "api"

router = routers.DefaultRouter()
router.register(prefix=r"posts", viewset=views.PostsViewset, basename="post")
router.register(prefix=r"comments", viewset=views.CommentViewset, basename="comment")


urlpatterns = [
    path('token/', AddUsernameTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

    path('api/', include('rest_framework.urls', namespace="rest_framework")),
    path('api/', include('api.urls', namespace='api')),
    path('', include('users.urls', namespace='user')),
    path('', include('posts.urls', namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('add-post/', views.CreatePostView.as_view(), name='add_post'),
    path('<int:pk>/', views.PostsView.as_view(), name='post_detail'),
    path('<int:post_id>/add_comment/', views.AddCommentToPostView.as_view(), name='add_post_comment'),
    path('<int:pk>/delete-post/', views.DeletePostView.as_view(), name='delete_post'),
    path('<int:post_id>/<int:comment_id>/', views.AddCommentToCommentView.as_view(), name='add_comment_comment'),
    path('<int:pk>/delete-comment', views.DeleteCommentView.as_view(), name='delete_comment'),
]

posts/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.core.exceptions import ValidationError
from services import (get_path_upload_comments_images, 
                      get_path_upload_textfile, 
                      validate_size_upload_textfile, 
                      validate_upload_comments_images)

from users.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255)
    body = models.TextField()
    url = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        db_table = "posts"
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ['-created_at']


    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    image = models.ImageField(upload_to=get_path_upload_comments_images, null=True, blank=True)
    file = models.FileField(upload_to=get_path_upload_textfile, 
                            null=True, 
                            blank=True, 
                            validators=[
                                FileExtensionValidator(allowed_extensions=["txt"]),
                                validate_size_upload_textfile,
                            ])
    url = models.URLField(null=True, blank=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        db_table = "comments"
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ['-created_at']


    def __str__(self):
        return f"Comment by {self.user} on {self.post}"
    

    def clean(self):
        if self.parent:
            if self.parent.post != self.post:
                raise ValidationError("Родительский комментарий должен принадлежать тому же посту.")
        super().clean()
    

    def save(self, *args, **kwargs):
        if self.image and hasattr(self.image, 'file'):
            self.image = validate_upload_comments_images(self.image.file)
        super().save(*args, **kwargs)

posts/forms.py
import bleach
from django import forms
from django.core.validators import RegexValidator, EmailValidator, URLValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from captcha.fields import CaptchaField

from posts.models import Comment, Post
from services import validate_size_upload_textfile, validate_upload_comments_images


ALLOWED_TAGS = ['a', 'code', 'i', 'strong']
ALLOWED_ATTRIBUTES = {'a': ['href', 'title']}


class AddCommentForm(forms.ModelForm):
    parent_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    user_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'autofocus': True,
                   'placeholder': 'Введите ваше имя',
                   'class': 'form-control'}),
        label='User Name',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message=_('User name can only contain letters and numbers.')
            )
        ]
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Введите ваш email',
                   'class': 'form-control'}),
        label='E-mail',
        validators=[EmailValidator()]
    )

    home_page = forms.URLField(
        widget=forms.URLInput(
            attrs={'placeholder': 'Введите вашу страничку',
                   'class': 'form-control'}),
        label='Home Page',
        required=False,
        validators=[URLValidator()]
    )

    image = forms.ImageField(required=False)
    file = forms.FileField(required=False)

    captcha = CaptchaField()

    text = forms.CharField(
        label='Text',
        widget=forms.Textarea(
            attrs={'rows': 4, 'cols': 40, 'class': 'form-control', 'id': 'id_body'}),
        help_text=_('You can use the following HTML tags: a, i, strong, code.')
    )

    class Meta:
        model = Comment
        fields = ['user_name', 'email', 'home_page', 'captcha', 'text', 'parent_id']



    def clean(self):
        cleaned_data = super().clean()

        user = self.initial['user']

        if not user.is_authenticated:
            raise ValidationError(_('Вы должны войти в систему, чтобы оставлять комментарии.'))

        entered_username = cleaned_data.get('user_name')
        entered_email = cleaned_data.get('email')


        if entered_username != user.username:
            raise ValidationError(_('Введённое имя пользователя не соответствует текущему пользователю.'))
        if entered_email != user.email:
            raise ValidationError(_('Введённый email не соответствует текущему пользователю.'))

        image = cleaned_data.get('image')
        if image:
            validate_upload_comments_images(image)

        file = cleaned_data.get('file')
        if file:
            validate_size_upload_textfile(file)

        return cleaned_data


class AddPostForm(forms.ModelForm):
    user_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'autofocus': True,
                   'placeholder': 'Введите ваше имя',
                   'class': 'form-control'}),
        label='User Name',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message=_('User name can only contain letters and numbers.')
            )
        ]
    )

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Название поста',
                   'class': 'form-control'}),
        label='Title'
    )

    body = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 4, 'cols': 40, 'class': 'form-control', 'id': 'id_body'}),
        label='Text',
        help_text=_('You can use the following HTML tags: a, i, strong, code.')
    )

    url = forms.URLField(
        widget=forms.URLInput(
            attrs={'placeholder': 'Введите вашу страничку',
                   'class': 'form-control'}),
        label='Home Page',
        required=False,
        validators=[URLValidator()])

    class Meta:
        model = Post
        fields = ['user_name', 'title', 'body', 'url']

    def clean_body(self):
        body = self.cleaned_data.get('body')

        allowed_tags = ['a', 'i', 'strong', 'code']
        cleaned_body = bleach.clean(body, tags=allowed_tags, strip=False)

        if body != cleaned_body:
            raise ValidationError(_('Текст содержит запрещенные HTML-теги или некорректные атрибуты.'))

        return cleaned_body

    def clean(self):
        cleaned_data = super().clean()

        user = self.initial['user']
        if not user.is_authenticated:
            raise ValidationError(_('Вы должны войти в систему, чтобы оставлять комментарии.'))

        entered_username = cleaned_data.get('user_name')
        if entered_username != user.username:
            raise ValidationError(_('Введённое имя пользователя не соответствует текущему пользователю.'))

        return cleaned_data

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.core.cache import cache
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView, DetailView, FormView, ListView
from posts.forms import AddCommentForm, AddPostForm

from posts.models import Comment, Post
from posts.search import search_posts


class MainView(ListView):
    model = Post
    template_name = 'base/main_page.html'
    context_object_name = "posts"
    paginate_by = 3
    allow_empty = True


    def get_queryset(self):
        order_by = self.request.GET.get("order_by")
        query = self.request.GET.get("q")
        cache_key = f"posts_{order_by}_{query}"

        posts = cache.get(cache_key)
        if posts is None:
            if query:
                posts = search_posts(query)
            else:
                posts = super().get_queryset()

            if order_by:
                if order_by == "username":
                    posts = posts.order_by("user__username")
                elif order_by == "email":
                    posts = posts.order_by("user__email")
                elif order_by == "news":
                    posts = posts.order_by("-created_at")
                elif order_by == "oldest":
                    posts = posts.order_by("created_at")

            cache.set(cache_key, posts, 60 * 15)
        return posts


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Главная Страница"
        return context



class PostsView(DetailView):
    model = Post
    template_name = 'posts/post_page.html'
    context_object_name = 'post'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.object
        comments = Comment.objects.filter(post=post, parent__isnull=True).order_by('created_at')

        paginator = Paginator(comments, 25)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context["title"] = "Комментарии"
        context['form'] = AddCommentForm()
        context['messages'] = messages.get_messages(self.request)
        return context


class CreatePostView(LoginRequiredMixin, FormView):
    form_class = AddPostForm
    template_name = 'posts/create_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AddPostForm()
        context['title'] = 'Добавить пост'
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {'user': self.request.user}
        return kwargs

    def form_valid(self, form):
        post = Post.objects.create(
            user=self.request.user,
            title=form.cleaned_data['title'],
            body=form.cleaned_data['body'],
            url=form.cleaned_data['url']
        )

        messages.success(self.request, 'Ваш пост был создан успешно.')
        return redirect(reverse('posts:post_detail', args=[post.id]))


    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f'{error}')
        return self.render_to_response(self.get_context_data(form=form))



class AddCommentToPostView(LoginRequiredMixin, FormView):

    def post(self, request, *args, **kwargs):
        post_id = self.kwargs['post_id']
        post = get_object_or_404(Post, pk=post_id)
        form = AddCommentForm(request.POST, request.FILES, initial={'user': request.user})

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.url = form.cleaned_data["home_page"]
            comment.body = form.cleaned_data["text"]
            comment.image = form.cleaned_data.get("image") 
            comment.file = form.cleaned_data.get("file")
            comment.save()

            messages.success(request, 'Ваш комментарий добавлен.')
            return JsonResponse({
                'success': True,
                'user': str(request.user),
                'comment': comment.body,
                'created_at': comment.created_at.strftime('%Y-%m-%d %H:%M:%S'),
            })

        errors = {field: errors for field, errors in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors}, status=400)
    


class AddCommentToCommentView(LoginRequiredMixin, FormView):

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs['post_id'])
        parent_comment = get_object_or_404(Comment, pk=self.kwargs['comment_id'])
        form = AddCommentForm(request.POST, request.FILES, initial={'user': request.user})

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.url = form.cleaned_data["home_page"]
            comment.body = form.cleaned_data["text"]
            comment.image = form.cleaned_data.get("image") 
            comment.file = form.cleaned_data.get("file")
            comment.parent = parent_comment
            comment.save()

            messages.success(request, 'Ваш комментарий добавлен.')
            return JsonResponse({
                'success': True,
                'user': str(request.user),
                'comment': comment.body,
                'created_at': comment.created_at.strftime('%Y-%m-%d %H:%M:%S'),
            })


        errors = {field: errors for field, errors in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors}, status=400)

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_id = self.kwargs.get('post_id')
        comment_id = self.kwargs.get('comment_id')

        context['post'] = get_object_or_404(Post, pk=post_id)
        context['comment'] = get_object_or_404(Comment, pk=comment_id)
        context['title'] = 'Ответить на комментарий'
        return context


class DeletePostView(UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:main')

    def test_func(self):
        post = self.get_object()
        return self.request.user == post.user or self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        messages.success(request, 'Пост успешно удалён.')
        return HttpResponseRedirect(self.get_success_url())
    

class DeleteCommentView(UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        comment = self.get_object()
        return self.request.user == comment.user or self.request.user.is_superuser

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        messages.success(request, 'Комментарий успешно удалён.')
        return redirect(request.META["HTTP_REFERER"])

templates/posts/add_comment.html
{% extends "base/base.html" %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            <h2 class="text-center mb-4">Добавить комментарий</h2>
                            
                            <form action="{% if comment.id %}{% url 'posts:add_comment_comment' post.id comment.id %}{% else %}{% url 'posts:add_post_comment' post.id %}{% endif %}" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-dark btn-block">Добавить</button>
                            </form>

                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/posts/comment.html
{% load static %}


<div class="comment-box" style="margin-left: {{ level }}px;">
    <div class="comment-header">
        {% if comment.user.avatar %}
            <img src="{{ comment.user.avatar.url }}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
        {% else %}
            <img src="{% static 'baseavatar.jpg' %}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
        {% endif %}
        <div class="comment-info">
            <strong>{{ comment.user.username }}</strong>
            <p class="card-text mb-0">{{ comment.user.email }}</p>
            <span class="comment-date">{{ comment.created_at|date:"d.m.y H:i" }}</span>
        </div>
    </div>

    <div class="comment-body">
        <div class="comment-body-content">
            {% autoescape off %}
                <p>{{ comment.body }}</p>
            {% endautoescape %}
            
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-secondary open-comment-comment-modal" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" data-url="{% url 'posts:add_comment_comment' post.id comment.id %}">
                    Ответить на комментарий
                </button>
            {% endif %}
            
            {% if user.id == comment.user.id %}
                <a href="{% url 'posts:delete_comment' comment.pk %}" class="btn btn-primary">Удалить Коммент</a>
            {% endif %}

        </div>
        <div class="comment-image-wrapper">
            {% if comment.image %}
                <img src="{{ comment.image.url }}" alt="Comment Image" class="comment-image">
            {% endif %}
            
            {% if comment.file %}
                <div class="comment-file">
                    <img src="{% static 'file_icon.png' %}" alt="Comment File" class="comment-image">
                    <a href="{{ comment.file.url }}">Скачать файл</a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% if comment.replies %}
    <div class="comment-replies">
        {% for child_comment in comment.replies.all %}
            {% include 'posts/comment.html' with comment=child_comment level=level|add:"20" %}
        {% endfor %}
    </div>
{% endif %}

templates/posts/comment_image.html
{% if comment.image %}
    <a href="{{ comment.image.url }}" data-lightbox="comment-images" data-title="Комментарий от {{ comment.user.username }}">
        <img src="{{ comment.image.url }}" alt="Комментарий от {{ comment.user.username }}" class="img-thumbnail" style="margin: 5px;">
    </a>
{% endif %}

{% if comment.replies %}
    {% for child_comment in comment.replies.all %}
        {% include 'posts/comment_image.html' with comment=child_comment %}
    {% endfor %}
{% endif %}

templates/posts/create_post.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row mt-1">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            <h2 class="text-center mb-4">Добавить Пост</h2>

                            <form method="post">
                                {% csrf_token %}
                                
                                <div class="form-group mb-3">
                                    <label for="id_user_name" class="form-label">Введите ваш юзернейм</label>
                                    {{ form.user_name }}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_title" class="form-label">Введите заголовок поста</label>
                                    {{ form.title }}
                                </div>

                                <div class="btn-group mb-3" role="group" aria-label="HTML Tags">
                                    <button type="button" class="btn btn-outline-secondary" onclick="insertTag('i')">[i]</button>
                                    <button type="button" class="btn btn-outline-secondary" onclick="insertTag('strong')">[strong]</button>
                                    <button type="button" class="btn btn-outline-secondary" onclick="insertTag('code')">[code]</button>
                                    <button type="button" class="btn btn-outline-secondary" onclick="insertTag('a', true)">[a]</button>
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_body" class="form-label">Введите текст поста</label>
                                    {{ form.body }}
                                </div>

                                <div class="form-group mb-3">
                                    <label for="id_url" class="form-label">Введите вашу страницу (опционально)</label>
                                    {{ form.url }}
                                </div>

                                <button type="submit" class="btn btn-dark btn-block">Добавить</button>
                            </form>

                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/posts/partial_comment_form.html
<form id="commentForm" method="post" action="{% url 'posts:add_post_comment' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Добавить комментарий</button>
</form>

templates/posts/post_page.html
{% extends "base/base.html" %}
{% load static %}
{% load posts_tags %}

{% block content %}
    <div class="post-detail">
        <h1>{{ post.title }}</h1>
        {% autoescape off %}
            <p>{{ post.body }}</p>
        {% endautoescape %}
        <strong>Автор: {{ post.user.username }}</strong>
        <p>{{ post.user.email }}</p>
        <p>Создан: {{ post.created_at|date:"H:i d.m.y" }}</p>
        

        {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary open-post-comment-modal" data-post-id="{{ post.id }}" data-url="{% url 'posts:add_post_comment' post.id %}">
                Комментировать пост
            </button>
        {% endif %}

        {% if user.id == post.user.id %}
            <a href="{% url 'posts:delete_post' post.pk %}" class="btn btn-primary">Удалить пост</a>
        {% endif %}

        {% if post.comments.all %}
            <button type="button" class="btn btn-dark" id="openGalleryButton">
                Все фото поста
            </button>
        {% endif %}
    </div>

    <div class="comments-section">
        <h3>Комментарии:</h3>
        {% for comment in page_obj %}
            {% include 'posts/comment.html' with comment=comment level=0 %}
        {% endfor %}
        

        {% include "base/notifications.html" %}
        {% include "base/comment_paginator.html" %}
        {% include "base/modal_form.html" %}
        {% include "base/modal_foto.html" %}

    </div>
{% endblock %}