api/urls.py
from rest_framework import routers
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from django.urls import path, include
from api import views
from api.token_view import AddUsernameTokenObtainPairView


app_name = "api"

router = routers.DefaultRouter()
router.register(prefix=r"posts", viewset=views.PostsViewset, basename="post")
router.register(prefix=r"comments", viewset=views.CommentViewset, basename="comment")


urlpatterns = [
    path('token/', AddUsernameTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

    path('api/', include('rest_framework.urls', namespace="rest_framework")),
    path('api/', include('api.urls', namespace='api')),
    path('', include('users.urls', namespace='user')),
    path('', include('posts.urls', namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('add-post/', views.CreatePostView.as_view(), name='add_post'),
    path('<int:pk>/', views.PostsView.as_view(), name='post_detail'),
    path('<int:post_id>/add_comment/', views.AddCommentToPostView.as_view(), name='add_post_comment'),
    path('<int:pk>/delete-post/', views.DeletePostView.as_view(), name='delete_post'),
    path('<int:post_id>/<int:comment_id>/', views.AddCommentToCommentView.as_view(), name='add_comment_comment'),
    path('<int:pk>/delete-comment', views.DeleteCommentView.as_view(), name='delete_comment'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('registration/', view=views.UserRegistrationView.as_view(), name='registration'),
    path('login/', view=views.UserLoginView.as_view(), name='login'),
    path('logout/', view=views.UserLogoutView.as_view(), name='logout'),
    path('profile/', view=views.UserProfileView.as_view(), name='profile'),
]

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "css/pagination.css" %}">
    <link rel="stylesheet" href="{% static "css/cards-comments.css" %}">
    <link rel="stylesheet" href="{% static "css/buttons.css" %}">
    <link rel="stylesheet" href="{% static "css/posts.css" %}">
    <link rel="stylesheet" href="{% static "css/lightbox.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'posts:main' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:login' %}">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:registration' %}">Регистрация</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:logout' %}">Выйти</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url "posts:main" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    {% include "base/notifications.html" %}

    {% block content %}
    {% endblock %}

    <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "js/jquery-ajax.js" %}"></script>
    <script src="{% static "js/lightbox.js" %}"></script>
    <script src="{% static "js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
</body>
</html>

templates/base/comment_paginator.html
{% load static %}
{% load posts_tags %}

{% if page_obj %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <!-- Кнопка "Начало" -->
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="?page=1">&laquo; начало</a>
            </li>

            <!-- Кнопка "Назад" -->
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% else %}#{% endif %}">Назад</a>
            </li>

            <!-- Номера страниц -->
            {% for page in page_obj.paginator.page_range %}
                {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <!-- Кнопка "Вперед" -->
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% else %}#{% endif %}">Следующая</a>
            </li>

            <!-- Кнопка "Конец" -->
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">конец &raquo;</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}

templates/base/main_page.html
{% extends "base/base.html" %}
{% load static %}
{% load posts_tags %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">

        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>
            
            {% if user.is_authenticated %}
                <a href="{% url 'posts:add_post' %}" class="btn btn-dark">Добавить пост</a>
            {% endif %}

            <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == "default" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="username" {% if request.GET.order_by == "username" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        По имени пользователя
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="email" {% if request.GET.order_by == "email" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        По email пользователя
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="news" {% if request.GET.order_by == "news" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Сначала новый
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="oldest" {% if request.GET.order_by == "oldest" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        Сначала старые
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>

        {% if request.GET.q %}
        <h2 class="font-nosifer mt-5 pt-5 text-center">Результат поиска по запросу "{{ request.GET.q }}"</h2>
            {% if not posts %}
                <h1 class="font-nosifer mt-5 pt-5 text-center">По запросу ничего не найдено...</h1>
            {% endif %}
        {% endif %}

        {% for post in posts %}
            <div class="col-lg-12 p-4">
                <div class="card border-primary rounded custom-shadow custom-card">
                    <div class="card-body custom-card-body">
                        <a href="{% url 'posts:post_detail' post.pk %}">
                            <h5 class="card-title">
                                {% autoescape off %}
                                    {% if post.headline %}
                                        {{ post.headline|truncatechars:100 }}
                                    {% else %}
                                        {{ post.title|truncatechars:40 }}
                                    {% endif %}
                                {% endautoescape %}
                            </h5>
                        </a>
                        <div class="d-flex align-items-center">
                            {% if post.user.avatar %}
                                <img src="{{ post.user.avatar.url }}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
                            {% else %}
                                <img src="{% static "baseavatar.jpg" %}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
                            {% endif %}
                            <p class="card-text mb-0">{{ post.user.username }}</p>
                        </div>
                        <strong>{{ post.user.email }}</strong>
                        <p class="card-text">
                            {% autoescape off %}
                                {% if post.bodyline %}
                                    {{ post.bodyline|truncatechars:100 }}
                                {% else %}
                                    {{ post.body|truncatechars:100 }}
                                {% endif %}
                            {% endautoescape %}

                        </p>
                        <p class="created_at">Создан: {{ post.created_at }}</p>
                    </div>
                </div>
            </div>
        
        {% endfor %}
        
    </div>
    
    {% include "base/post_paginator.html" %}

</div>
{% endblock content %}

templates/base/modal_form.html
{% load static %}


<div class="modal fade" id="commentModal" tabindex="-1" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalLabel">Добавить комментарий</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form id="commentForm" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="mb-3">
                {{ form.user_name.label_tag }}
                {{ form.user_name }}
              </div>
              <div class="mb-3">
                {{ form.email.label_tag }}
                {{ form.email }}
              </div>
              <div class="mb-3">
                {{ form.home_page.label_tag }}
                {{ form.home_page }}
              </div>
    
              <div class="btn-group mb-3" role="group" aria-label="HTML Tags">
                <button type="button" class="btn btn-outline-secondary">[i]</button>
                <button type="button" class="btn btn-outline-secondary">[strong]</button>
                <button type="button" class="btn btn-outline-secondary">[code]</button>
                <button type="button" class="btn btn-outline-secondary">[a]</button>
              </div>
    
              <div class="mb-3">
                {{ form.text.label_tag }}
                {{ form.text }}
              </div>
              <div class="mb-3">
                {{ form.image.label_tag }}
                {{ form.image }}
              </div>
              <div class="mb-3">
                {{ form.file.label_tag }}
                {{ form.file }}
              </div>
    
              <div class="mb-3">
                {{ form.captcha.label_tag }}
                {{ form.captcha }}
              </div>
              <input type="hidden" id="parentId" name="parent_id" value="">
              <button type="submit" class="btn btn-primary">Добавить комментарий</button>

              <button type="button" id="preview-comment" class="btn btn-info">Предпросмотр</button>
              <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
          {% include "base/preview_form.html" %}
        <div class="error-message"></div>  </div>
    </div>
  </div>
</div>

templates/base/modal_foto.html
<!-- Модальное окно для просмотра изображений -->
<div class="modal fade" id="imageGalleryModal" tabindex="-1" aria-labelledby="imageGalleryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="imageGalleryModalLabel">Галерея изображений</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="lightbox-gallery">
                    {% for comment in page_obj %}
                    {% include 'posts/comment_image.html' with comment=comment %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/base/notifications.html
{% load static %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success alert-dismissible fade show custom-shadow" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' or message.tags == 'error' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success alert-dismissible fade show custom-shadow" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        
        </div>
    </div>
</div>

templates/base/post_paginator.html
{% load posts_tags %}

{% if posts %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <div class="custom-shadow d-flex">

            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link rounded-start" href="?page=1">&laquo; начало</a>
            </li>

            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% else %}#{% endif %}">Назад</a>
            </li>

            {% for page in page_obj.paginator.page_range %}
                {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% else %}#{% endif %}">Следующая</a>
            </li>

            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">конец &raquo;</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}

templates/base/preview_form.html
<div class="modal fade" id="previewModal" tabindex="-1" aria-labelledby="previewModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="previewModalLabel">Предпросмотр комментария</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <div id="preview-content">
                    <strong id="preview-username"></strong>
                    <p id="preview-email"></p>
                    <p id="preview-comment-body"></p>
                    <img id="preview-image" src="" alt="Preview Image" style="display:none; max-width: 100%;"/>
                    <a id="preview-file" href="" target="_blank" style="display:none;">Предпросмотр файла</a>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>