api/urls.py
from rest_framework import routers
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from django.urls import path, include
from api import views
from api.token_view import AddUsernameTokenObtainPairView


app_name = "api"

router = routers.DefaultRouter()
router.register(prefix=r"posts", viewset=views.PostsViewset, basename="post")
router.register(prefix=r"comments", viewset=views.CommentViewset, basename="comment")


urlpatterns = [
    path('token/', AddUsernameTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('', include(router.urls)),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from app import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

    path('api/', include('rest_framework.urls', namespace="rest_framework")),
    path('api/', include('api.urls', namespace='api')),
    path('', include('users.urls', namespace='user')),
    path('', include('posts.urls', namespace='post')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('add-post/', views.CreatePostView.as_view(), name='add_post'),
    path('<int:pk>/', views.PostsView.as_view(), name='post_detail'),
    path('<int:post_id>/add_comment/', views.AddCommentToPostView.as_view(), name='add_post_comment'),
    path('<int:pk>/delete-post/', views.DeletePostView.as_view(), name='delete_post'),
    path('<int:post_id>/<int:comment_id>/', views.AddCommentToCommentView.as_view(), name='add_comment_comment'),
    path('<int:pk>/delete-comment', views.DeleteCommentView.as_view(), name='delete_comment'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'


urlpatterns = [
    path('registration/', view=views.UserRegistrationView.as_view(), name='registration'),
    path('login/', view=views.UserLoginView.as_view(), name='login'),
    path('logout/', view=views.UserLogoutView.as_view(), name='logout'),
    path('profile/', view=views.UserProfileView.as_view(), name='profile'),
]

posts/forms.py
import bleach
from django import forms
from django.core.validators import RegexValidator, EmailValidator, URLValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from captcha.fields import CaptchaField

from posts.models import Comment, Post
from services import validate_size_upload_textfile, validate_upload_comments_images


ALLOWED_TAGS = ['a', 'code', 'i', 'strong']
ALLOWED_ATTRIBUTES = {'a': ['href', 'title']}


class AddCommentForm(forms.ModelForm):
    parent_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    user_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'autofocus': True,
                   'placeholder': 'Введите ваше имя',
                   'class': 'form-control'}),
        label='User Name',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message=_('User name can only contain letters and numbers.')
            )
        ]
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Введите ваш email',
                   'class': 'form-control'}),
        label='E-mail',
        validators=[EmailValidator()]
    )

    home_page = forms.URLField(
        widget=forms.URLInput(
            attrs={'placeholder': 'Введите вашу страничку',
                   'class': 'form-control'}),
        label='Home Page',
        required=False,
        validators=[URLValidator()]
    )

    image = forms.ImageField(required=False)
    file = forms.FileField(required=False)

    captcha = CaptchaField()

    text = forms.CharField(
        label='Text',
        widget=forms.Textarea(
            attrs={'rows': 4, 'cols': 40, 'class': 'form-control', 'id': 'id_body'}),
        help_text=_('You can use the following HTML tags: a, i, strong, code.')
    )

    class Meta:
        model = Comment
        fields = ['user_name', 'email', 'home_page', 'captcha', 'text', 'parent_id']



    def clean(self):
        cleaned_data = super().clean()

        user = self.initial['user']

        if not user.is_authenticated:
            raise ValidationError(_('Вы должны войти в систему, чтобы оставлять комментарии.'))

        entered_username = cleaned_data.get('user_name')
        entered_email = cleaned_data.get('email')


        if entered_username != user.username:
            raise ValidationError(_('Введённое имя пользователя не соответствует текущему пользователю.'))
        if entered_email != user.email:
            raise ValidationError(_('Введённый email не соответствует текущему пользователю.'))

        image = cleaned_data.get('image')
        if image:
            validate_upload_comments_images(image)

        file = cleaned_data.get('file')
        if file:
            validate_size_upload_textfile(file)

        return cleaned_data


class AddPostForm(forms.ModelForm):
    user_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'autofocus': True,
                   'placeholder': 'Введите ваше имя',
                   'class': 'form-control'}),
        label='User Name',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message=_('User name can only contain letters and numbers.')
            )
        ]
    )

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Название поста',
                   'class': 'form-control'}),
        label='Title'
    )

    body = forms.CharField(
        widget=forms.Textarea(
            attrs={'rows': 4, 'cols': 40, 'class': 'form-control', 'id': 'id_body'}),
        label='Text',
        help_text=_('You can use the following HTML tags: a, i, strong, code.')
    )

    url = forms.URLField(
        widget=forms.URLInput(
            attrs={'placeholder': 'Введите вашу страничку',
                   'class': 'form-control'}),
        label='Home Page',
        required=False,
        validators=[URLValidator()])

    class Meta:
        model = Post
        fields = ['user_name', 'title', 'body', 'url']

    def clean_body(self):
        body = self.cleaned_data.get('body')

        allowed_tags = ['a', 'i', 'strong', 'code']
        cleaned_body = bleach.clean(body, tags=allowed_tags, strip=False)

        if body != cleaned_body:
            raise ValidationError(_('Текст содержит запрещенные HTML-теги или некорректные атрибуты.'))

        return cleaned_body

    def clean(self):
        cleaned_data = super().clean()

        user = self.initial['user']
        if not user.is_authenticated:
            raise ValidationError(_('Вы должны войти в систему, чтобы оставлять комментарии.'))

        entered_username = cleaned_data.get('user_name')
        if entered_username != user.username:
            raise ValidationError(_('Введённое имя пользователя не соответствует текущему пользователю.'))

        return cleaned_data

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from PIL import Image
from .models import User


class UserAuthForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'avatar')


    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control",
                "placeholder": "Введите ваше имя пользователя",
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                "class": "form-control",
                "placeholder": "Введите ваш пароль",
            }
        ),
    )


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )
    
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                "class": "form-control",
                "placeholder": "Введите ваше имя пользователя",
            }
        ))
    
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваш email",
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Введите ваш пароль",
            }
        ))
    
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "Повторите ваш пароль",
            }
        ))



class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "avatar",
            "username",
            "email"
        )

    avatar = forms.ImageField(required=False)
    username = forms.CharField()
    email = forms.CharField()


    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar')

        if avatar:
            try:
                img = Image.open(avatar)
            except Exception:
                raise ValidationError("Не удалось открыть изображение.")

            max_width = 320
            max_height = 240

            if img.width > max_width or img.height > max_height:
                raise ValidationError(
                    f"Изображение должно быть не более {max_width}x{max_height} пикселей."
                )

        return avatar

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static "css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "css/my_footer_css.css" %}">
    <link rel="stylesheet" href="{% static "css/pagination.css" %}">
    <link rel="stylesheet" href="{% static "css/cards-comments.css" %}">
    <link rel="stylesheet" href="{% static "css/buttons.css" %}">
    <link rel="stylesheet" href="{% static "css/posts.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'posts:main' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:login' %}">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:registration' %}">Регистрация</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:logout' %}">Выйти</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url "posts:main" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    {% include "notifications.html" %}

    {% block content %}
    {% endblock %}

    <script src="{% static "js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "js/jquery-ajax.js" %}"></script>
    <script src="{% static "js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
</body>
</html>

templates/comment.html
{% load static %}

<div class="comment-box" style="margin-left: {{ level }}px;">
    <div class="comment-header">
        {% if comment.user.avatar %}
            <img src="{{ comment.user.avatar.url }}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
        {% else %}
            <img src="{% static "baseavatar.jpg" %}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
        {% endif %}
        <div class="comment-info">
            <strong>{{ comment.user.username }}</strong>
            <span class="comment-date">{{ comment.created_at|date:"d.m.y H:i" }}</span>
        </div>
    </div>

    <div class="comment-body">
        <div class="comment-body-content">
            <p>{{ comment.body }}</p>
            <a href="#" class="btn btn-outline-info">Ответить</a>
        </div>
        <div class="comment-image-wrapper">
            {% if comment.image %}
                <img src="{{ comment.image.url }}" alt="Comment Image" class="comment-image">
            {% endif %}
            {% if comment.file %}
                <div class="comment-file">
                    <img src="{% static 'file_icon.png' %}" alt="Comment File" class="comment-image">
                    <a href="{{ comment.file.url }}">Скачать файл</a>
                </div>
            {% endif %}
        </div>
    </div>

    {% if comment.replies %}
        <div class="comment-children">
            {% for child_comment in comment.replies.all %}
                {% include 'comment.html' with comment=child_comment level=level|add:"20" %}
            {% endfor %}
        </div>
    {% endif %}
</div>

templates/login.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            <h2 class="text-center mb-4">Авторизация</h2>

                            <form action="{% url "users:login" %}" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" 
                                    class="btn btn-dark btn-block">Войти</button>
                            </form>

                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Dzencode</p>
    </div>
</footer>
{% endblock footer %}

templates/main_page.html
{% extends "base.html" %}
{% load static %}
{% load posts_tags %}


{% block content %}
<div class="container">
    <div class="row justify-content-center">

        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>

            <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == "default" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="username" {% if request.GET.order_by == "username" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        По имени пользователя
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="email" {% if request.GET.order_by == "email" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        По email пользователя
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="news" {% if request.GET.order_by == "news" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Сначала новый
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="oldest" {% if request.GET.order_by == "oldest" %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        Сначала старые
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>

        {% if request.GET.q %}
        <h2 class="font-nosifer mt-5 pt-5 text-center">Результат поиска по запросу "{{ request.GET.q }}"</h2>
            {% if not posts %}
                <h1 class="font-nosifer mt-5 pt-5 text-center">По запросу ничего не найдено...</h1>
            {% endif %}
        {% endif %}

        {% for post in posts %}
            <div class="col-lg-12 p-4">
                <div class="card border-primary rounded custom-shadow custom-card">
                    <div class="card-body custom-card-body">
                        <a href="{% url 'posts:post_detail' post.pk %}">
                            <h5 class="card-title">
                                {% autoescape off %}
                                    {% if post.headline %}
                                        {{ post.headline|truncatechars:100 }}
                                    {% else %}
                                        {{ post.title|truncatechars:40 }}
                                    {% endif %}
                                {% endautoescape %}
                            </h5>
                        </a>
                        <div class="d-flex align-items-center">
                            {% if post.user.avatar %}
                                <img src="{{ post.user.avatar.url }}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
                            {% else %}
                                <img src="{% static "baseavatar.jpg" %}" alt="Avatar" class="rounded-circle me-2" width="40" height="40">
                            {% endif %}
                            <p class="card-text mb-0">{{ post.user.username }}</p>
                        </div>
                        <p class="card-text">
                            {% autoescape off %}
                                {% if post.bodyline %}
                                    {{ post.bodyline|truncatechars:100 }}
                                {% else %}
                                    {{ post.body|truncatechars:100 }}
                                {% endif %}
                            {% endautoescape %}
                        </p>
                        <p class="created_at">Создан: {{ post.created_at }}</p>
                    </div>
                </div>
            </div>
        
        {% endfor %}
        
    </div>


    <!-- Paginator -->
    {% if posts %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center my-4">
            <div class="custom-shadow d-flex">

                <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% else %}#{% endif %}">Назад</a>
                </li>

                {% for page in page_obj.paginator.page_range %}
                    {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                        <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                            <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}


                <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                    <a class="page-link" href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% else %}#{% endif %}">Следующая</a>
                </li>
            </div>
        </ul>
    </nav>
    {% endif %}

</div>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-10 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                            <h2 class="text-center mb-4">Профайл</h2>

                            <form action="{% url "users:profile" %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <!-- Изображение -->
                                    <div class="col-md-12 mb-3 text-center">
                                        {% if user.avatar %}
                                            <img src="{{ user.avatar.url }}"
                                                 alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                 style="max-width: 150px;">
                                        {% else %}
                                            <img src="{% static 'baseavatar.jpg' %}"
                                                 alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                 style="max-width: 150px;">
                                        {% endif %}
                                        <input type="file" class="form-control mt-3" id="id_avatar" name="avatar" accept="image/*">
                                    </div>
                                    <!-- Username -->
                                    <div class="col-md-12 mb-3">
                                        <label for="id_username" class="form-label">Username</label>
                                        <input type="text" class="form-control" id="id_username"
                                            name="username"
                                            placeholder="Введите ваше имя пользователя" 
                                            value="{{ form.username.value }}" 
                                            required>
                                            {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                            {% endif %}
                                    </div>
                                    <!-- Email -->
                                    <div class="col-md-12 mb-3">
                                        <label for="id_email" class="form-label">Email*</label>
                                        <input type="email" class="form-control" id="id_email"
                                            name="email"
                                            placeholder="Введите ваш email *youremail@example.com" 
                                            value="{{ form.email.value }}"
                                            required>
                                            {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                            {% endif %}
                                    </div>
                                    <button type="submit" class="btn btn-dark">Сохранить</button>
                                </div>   
                            </form>

                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/registration.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-10">
            <div class="row">
                <div class="container mt-5">
                    <div class="row justify-content-center">
                        <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                            <h2 class="text-center mb-4">Регистрация</h2>

                            <form action="{% url "users:registration" %}" method='post'>
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit"
                                    class="btn btn-dark btn-block">Зарегистрироваться</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}